// wrappers/vue/src/Alert.vue
<script setup>
import { computed, ref } from 'vue';
import { cn } from '../classNames.js';

const props = defineProps({
  variant: { type: String, default: 'primary' },
  solid: Boolean,
  outline: Boolean,
  dismissible: Boolean,
  size: { type: String, default: '' },
  title: { type: String, default: '' },
});

const emit = defineEmits(['dismiss']);

const root = ref(null);
const visible = ref(true);
const leaving = ref(false);

const cls = computed(() =>
  cn(
    'alert',
    props.variant && (props.solid ? `alert--solid-${props.variant}` : props.outline ? `alert--outline-${props.variant}` : `alert--${props.variant}`),
    props.dismissible && 'alert--dismissible',
    props.size && `alert--${props.size}`
  )
);

function dismiss() {
  if (leaving.value) return;
  leaving.value = true;
  const el = root.value;
  if (el) {
    el.style.transition = 'opacity 0.2s ease, transform 0.2s ease';
    el.style.opacity = '0';
    el.style.transform = 'translateY(-8px)';
  }
  emit('dismiss');
  setTimeout(() => {
    visible.value = false;
  }, 200);
}
</script>

<template>
  <div v-if="visible" ref="root" class="alert" :class="cls" role="alert">
    <p v-if="title" class="alert__title">{{ title }}</p>
    <slot />
    <button v-if="dismissible" type="button" class="alert__close" aria-label="Close" @click="dismiss">×</button>
  </div>
</template>

// wrappers/react/src/Alert.jsx
import { forwardRef, useRef, useState } from 'react';
import { cx } from './classNames';
import { mergeRefs } from './utils';

const TruenoAlert = forwardRef(function TruenoAlert(
  {
    variant = 'primary',
    solid,
    outline,
    dismissible,
    size,
    title,
    icon,
    onDismiss,
    className,
    children,
    ...rest
  },
  ref
) {
  const nodeRef = useRef(null);
  const [leaving, setLeaving] = useState(false);
  const [gone, setGone] = useState(false);
  const setRefs = mergeRefs(ref, nodeRef);

  if (gone) return null;

  const handleDismiss = () => {
    if (leaving) return;
    setLeaving(true);
    const node = nodeRef.current;
    if (node) {
      node.style.transition = 'opacity 0.2s ease, transform 0.2s ease';
      node.style.opacity = '0';
      node.style.transform = 'translateY(-8px)';
    }
    if (typeof onDismiss === 'function') onDismiss();
    window.setTimeout(() => setGone(true), 200);
  };

  const classes = cx(
    'alert',
    variant && (solid ? `alert--solid-${variant}` : outline ? `alert--outline-${variant}` : `alert--${variant}`),
    dismissible && 'alert--dismissible',
    size && `alert--${size}`,
    className
  );

  return (
    <div ref={setRefs} className={classes} role="alert" {...rest}>
      {icon && <span className="alert__icon">{icon}</span>}
      {title && <p className="alert__title">{title}</p>}
      {children}
      {dismissible && (
        <button type="button" className="alert__close" aria-label="Close" onClick={handleDismiss}>
          ×
        </button>
      )}
    </div>
  );
});

export default TruenoAlert;
