// wrappers/vue/src/Badge.vue
<script setup>
import { computed } from 'vue';
import { cn } from '../classNames.js';

const props = defineProps({
  as: { type: String, default: 'span' },
  variant: { type: String, default: 'secondary' },
  soft: Boolean,
  outline: Boolean,
  pill: Boolean,
  dot: Boolean,
  count: Boolean,
  size: { type: String, default: '' },
});

const cls = computed(() =>
  cn(
    'badge',
    props.dot && 'badge--dot',
    props.count && 'badge--count',
    props.variant && (props.soft ? `badge--soft-${props.variant}` : props.outline ? `badge--outline-${props.variant}` : `badge--${props.variant}`),
    props.pill && 'badge--pill',
    props.size && `badge--${props.size}`
  )
);
</script>

<template>
  <component :is="as" :class="cls">
    <slot />
  </component>
</template>

// wrappers/react/src/Badge.jsx
import { forwardRef } from 'react';
import { cx } from './classNames';

const TruenoBadge = forwardRef(function TruenoBadge(
  {
    as: Tag = 'span',
    variant = 'secondary',
    soft,
    outline,
    pill,
    dot,
    count,
    size,
    className,
    children,
    ...rest
  },
  ref
) {
  const classes = cx(
    'badge',
    dot && 'badge--dot',
    count && 'badge--count',
    variant && (soft ? `badge--soft-${variant}` : outline ? `badge--outline-${variant}` : `badge--${variant}`),
    pill && 'badge--pill',
    size && `badge--${size}`,
    className
  );
  return (
    <Tag ref={ref} className={classes} {...rest}>
      {children}
    </Tag>
  );
});

export default TruenoBadge;
