// wrappers/vue/src/Button.vue
<script setup>
import { computed } from 'vue';
import { cn } from '../classNames.js';

const props = defineProps({
  as: { type: String, default: 'button' },
  variant: { type: String, default: '' },
  size: { type: String, default: '' },
});

const cls = computed(() =>
  cn('btn', props.variant && `btn--${props.variant}`, props.size && `btn--${props.size}`)
);
</script>

<template>
  <component :is="as" :class="cls">
    <slot />
  </component>
</template>

// wrappers/react/src/Button.jsx
import { forwardRef } from 'react';
import { cx } from './classNames';

const TruenoButton = forwardRef(function TruenoButton(
  { as: Tag = 'button', variant, size, className, children, ...rest },
  ref
) {
  return (
    <Tag ref={ref} className={cx('btn', variant && `btn--${variant}`, size && `btn--${size}`, className)} {...rest}>
      {children}
    </Tag>
  );
});

export default TruenoButton;
