// wrappers/vue/src/ThemeToggle.vue
<script setup>
import { onMounted, ref } from 'vue';

const dark = ref(false);

onMounted(() => {
  dark.value = document.body.classList.contains('theme--dark');
});

function toggle() {
  dark.value = !dark.value;
  if (window.Trueno && window.Trueno.Theme) {
    window.Trueno.Theme.set(dark.value);
  } else {
    document.body.classList.toggle('theme--dark', dark.value);
    try {
      localStorage.setItem('trueno-theme', dark.value ? 'dark' : 'light');
    } catch (e) {}
  }
}
</script>

<template>
  <button type="button" class="theme-toggle" :aria-pressed="String(dark)" @click="toggle">
    <slot>{{ dark ? '☀️' : '🌙' }}</slot>
  </button>
</template>

// wrappers/react/src/ThemeToggle.jsx
import { forwardRef, useState } from 'react';
import { cx } from './classNames';

const TruenoThemeToggle = forwardRef(function TruenoThemeToggle({ className, children, ...rest }, ref) {
  const [dark, setDark] = useState(
    () => typeof document !== 'undefined' && document.body.classList.contains('theme--dark')
  );

  const toggle = () => {
    const next = !dark;
    setDark(next);
    if (window.Trueno && window.Trueno.Theme) {
      window.Trueno.Theme.set(next);
    } else {
      document.body.classList.toggle('theme--dark', next);
      try {
        localStorage.setItem('trueno-theme', next ? 'dark' : 'light');
      } catch (e) {}
    }
  };

  return (
    <button ref={ref} type="button" className={cx('theme-toggle', className)} aria-pressed={dark} onClick={toggle} {...rest}>
      {children ?? (dark ? '☀️' : '🌙')}
    </button>
  );
});

export default TruenoThemeToggle;
